### ISSUE TITLE
Feedback Request: NTW03 protocols

### ISSUE THREAD

**Issue by yourlocaldaphne** [Techgrounds-Cloud-9/cloud-9-yourlocaldaphne#4]
**Feedback Request [Protocols]**
Permalink to file: [[LINK](https://github.com/Techgrounds-Cloud-9/cloud-9-yourlocaldaphne/tree/main/01_Fundamentals_1/sprint02_week_02/NTW03_protocols)]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by jairvaneer** [comment]
**Summary**
- Does the summary describe the subject matter fully?
- Yes
- Is the summary written in own words?
- Yes
- Is there crucial information missing in the summary?
- No
- Is the description clear enough?
- Yes

**Key Terminology**
- Are there missing key terms?
- No
- Are the key terms explained well?
- Yes

**Sources**
- Are the sources mentioned?
- Yes
- Are the mentioned sources correct?
- Ys

**Excercise**
(Where applicable)
- Is the result correct?
- Yes
- Are the experienced problems and solutions described well?
- Yes
